// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// crve_sandwich
arma::mat crve_sandwich(arma::mat X, arma::mat bread, arma::vec uhat, arma::umat clusterby, arma::ivec comb, arma::uvec G);
RcppExport SEXP wildclusterboot_crve_sandwich(SEXP XSEXP, SEXP breadSEXP, SEXP uhatSEXP, SEXP clusterbySEXP, SEXP combSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bread(breadSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type uhat(uhatSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type clusterby(clusterbySEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type comb(combSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(crve_sandwich(X, bread, uhat, clusterby, comb, G));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fix_cpp
arma::mat eigen_fix_cpp(arma::mat sandwich);
RcppExport SEXP wildclusterboot_eigen_fix_cpp(SEXP sandwichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type sandwich(sandwichSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fix_cpp(sandwich));
    return rcpp_result_gen;
END_RCPP
}
