# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crve_sandwich <- function(X, bread, uhat, clusterby, comb, G) {
    .Call('wildclusterboot_crve_sandwich', PACKAGE = 'wildclusterboot', X, bread, uhat, clusterby, comb, G)
}

eigen_fix_cpp <- function(sandwich) {
    .Call('wildclusterboot_eigen_fix_cpp', PACKAGE = 'wildclusterboot', sandwich)
}

