# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crve_sandwich <- function(X, bread, uhat, clusterby, comb, G) {
    .Call('wildclusterboot_crve_sandwich', PACKAGE = 'wildclusterboot', X, bread, uhat, clusterby, comb, G)
}

eigen_fix_cpp <- function(sandwich) {
    .Call('wildclusterboot_eigen_fix_cpp', PACKAGE = 'wildclusterboot', sandwich)
}

bread_cpp <- function(X) {
    .Call('wildclusterboot_bread_cpp', PACKAGE = 'wildclusterboot', X)
}

beta_cpp <- function(X, bread, y_wild) {
    .Call('wildclusterboot_beta_cpp', PACKAGE = 'wildclusterboot', X, bread, y_wild)
}

y_weights <- function(fitted_data, uhat, boot_weights, bootind) {
    .Call('wildclusterboot_y_weights', PACKAGE = 'wildclusterboot', fitted_data, uhat, boot_weights, bootind)
}

